version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: learning_platform
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      DATABASE_URL: postgresql://testuser:testpass@postgres:5432/learning_platform
      SECRET_KEY: dev-secret-key-change-in-production
    depends_on:
      - postgres

  course-service:
    build:
      context: ./course_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      DATABASE_URL: postgresql://testuser:testpass@postgres:5432/learning_platform
      SECRET_KEY: dev-secret-key-change-in-production
      USER_SERVICE_URL: http://user-service:5002
    depends_on:
      - postgres
      - user-service

volumes:
  postgres_data: